# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movieService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12movieService.proto\x12\x05proto\"\"\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"\x12\n\x10GetMoviesRequest\"1\n\x11GetMoviesResponse\x12\x1c\n\x06movies\x18\x01 \x03(\x0b\x32\x0c.proto.Movie\"#\n\x12\x43reateMovieRequest\x12\r\n\x05title\x18\x01 \x01(\t\"2\n\x13\x43reateMovieResponse\x12\x1b\n\x05movie\x18\x01 \x01(\x0b\x32\x0c.proto.Movie2\x94\x01\n\x0cMovieService\x12>\n\tGetMovies\x12\x17.proto.GetMoviesRequest\x1a\x18.proto.GetMoviesResponse\x12\x44\n\x0b\x43reateMovie\x12\x19.proto.CreateMovieRequest\x1a\x1a.proto.CreateMovieResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movieService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _globals['_MOVIE']._serialized_start=29
  _globals['_MOVIE']._serialized_end=63
  _globals['_GETMOVIESREQUEST']._serialized_start=65
  _globals['_GETMOVIESREQUEST']._serialized_end=83
  _globals['_GETMOVIESRESPONSE']._serialized_start=85
  _globals['_GETMOVIESRESPONSE']._serialized_end=134
  _globals['_CREATEMOVIEREQUEST']._serialized_start=136
  _globals['_CREATEMOVIEREQUEST']._serialized_end=171
  _globals['_CREATEMOVIERESPONSE']._serialized_start=173
  _globals['_CREATEMOVIERESPONSE']._serialized_end=223
  _globals['_MOVIESERVICE']._serialized_start=226
  _globals['_MOVIESERVICE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
