# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import movieService_pb2 as movieService__pb2


class MovieServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMovies = channel.unary_unary(
                '/proto.MovieService/GetMovies',
                request_serializer=movieService__pb2.GetMoviesRequest.SerializeToString,
                response_deserializer=movieService__pb2.GetMoviesResponse.FromString,
                )
        self.CreateMovie = channel.unary_unary(
                '/proto.MovieService/CreateMovie',
                request_serializer=movieService__pb2.CreateMovieRequest.SerializeToString,
                response_deserializer=movieService__pb2.CreateMovieResponse.FromString,
                )


class MovieServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMovies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MovieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMovies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMovies,
                    request_deserializer=movieService__pb2.GetMoviesRequest.FromString,
                    response_serializer=movieService__pb2.GetMoviesResponse.SerializeToString,
            ),
            'CreateMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMovie,
                    request_deserializer=movieService__pb2.CreateMovieRequest.FromString,
                    response_serializer=movieService__pb2.CreateMovieResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.MovieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MovieService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMovies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.MovieService/GetMovies',
            movieService__pb2.GetMoviesRequest.SerializeToString,
            movieService__pb2.GetMoviesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.MovieService/CreateMovie',
            movieService__pb2.CreateMovieRequest.SerializeToString,
            movieService__pb2.CreateMovieResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
