// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: hallService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Movie     *Movie `protobuf:"bytes,2,opt,name=movie,proto3" json:"movie,omitempty"`
	Capacity  int32  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Available int32  `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *Hall) Reset() {
	*x = Hall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hallService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hall) ProtoMessage() {}

func (x *Hall) ProtoReflect() protoreflect.Message {
	mi := &file_hallService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hall.ProtoReflect.Descriptor instead.
func (*Hall) Descriptor() ([]byte, []int) {
	return file_hallService_proto_rawDescGZIP(), []int{0}
}

func (x *Hall) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hall) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

func (x *Hall) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Hall) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

type CreateHallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Movie     *Movie `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	Capacity  int32  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Available int32  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *CreateHallRequest) Reset() {
	*x = CreateHallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hallService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHallRequest) ProtoMessage() {}

func (x *CreateHallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hallService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHallRequest.ProtoReflect.Descriptor instead.
func (*CreateHallRequest) Descriptor() ([]byte, []int) {
	return file_hallService_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHallRequest) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

func (x *CreateHallRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateHallRequest) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

type CreateHallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hall *Hall `protobuf:"bytes,1,opt,name=hall,proto3" json:"hall,omitempty"`
}

func (x *CreateHallResponse) Reset() {
	*x = CreateHallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hallService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHallResponse) ProtoMessage() {}

func (x *CreateHallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hallService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHallResponse.ProtoReflect.Descriptor instead.
func (*CreateHallResponse) Descriptor() ([]byte, []int) {
	return file_hallService_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHallResponse) GetHall() *Hall {
	if x != nil {
		return x.Hall
	}
	return nil
}

type GetHallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetHallRequest) Reset() {
	*x = GetHallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hallService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHallRequest) ProtoMessage() {}

func (x *GetHallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hallService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHallRequest.ProtoReflect.Descriptor instead.
func (*GetHallRequest) Descriptor() ([]byte, []int) {
	return file_hallService_proto_rawDescGZIP(), []int{3}
}

func (x *GetHallRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hall *Hall `protobuf:"bytes,1,opt,name=hall,proto3" json:"hall,omitempty"`
}

func (x *GetHallResponse) Reset() {
	*x = GetHallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hallService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHallResponse) ProtoMessage() {}

func (x *GetHallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hallService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHallResponse.ProtoReflect.Descriptor instead.
func (*GetHallResponse) Descriptor() ([]byte, []int) {
	return file_hallService_proto_rawDescGZIP(), []int{4}
}

func (x *GetHallResponse) GetHall() *Hall {
	if x != nil {
		return x.Hall
	}
	return nil
}

type UpdateHallAvailableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Available int32 `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *UpdateHallAvailableRequest) Reset() {
	*x = UpdateHallAvailableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hallService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHallAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHallAvailableRequest) ProtoMessage() {}

func (x *UpdateHallAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hallService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHallAvailableRequest.ProtoReflect.Descriptor instead.
func (*UpdateHallAvailableRequest) Descriptor() ([]byte, []int) {
	return file_hallService_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateHallAvailableRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateHallAvailableRequest) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

type UpdateHallAvailableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hall *Hall `protobuf:"bytes,1,opt,name=hall,proto3" json:"hall,omitempty"`
}

func (x *UpdateHallAvailableResponse) Reset() {
	*x = UpdateHallAvailableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hallService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHallAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHallAvailableResponse) ProtoMessage() {}

func (x *UpdateHallAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hallService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHallAvailableResponse.ProtoReflect.Descriptor instead.
func (*UpdateHallAvailableResponse) Descriptor() ([]byte, []int) {
	return file_hallService_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateHallAvailableResponse) GetHall() *Hall {
	if x != nil {
		return x.Hall
	}
	return nil
}

var File_hallService_proto protoreflect.FileDescriptor

var file_hallService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x68, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74,
	0x0a, 0x04, 0x48, 0x61, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61,
	0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x22, 0x71, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x35, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x04, 0x68, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x04, 0x68, 0x61, 0x6c, 0x6c, 0x22, 0x20,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x32, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x68, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x04,
	0x68, 0x61, 0x6c, 0x6c, 0x22, 0x4a, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61,
	0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x22, 0x3e, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x6c, 0x6c, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x04, 0x68, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x04, 0x68, 0x61, 0x6c, 0x6c,
	0x32, 0xe8, 0x01, 0x0a, 0x0b, 0x48, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x41, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x6c, 0x6c, 0x12, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x12, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a,
	0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x48, 0x61, 0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hallService_proto_rawDescOnce sync.Once
	file_hallService_proto_rawDescData = file_hallService_proto_rawDesc
)

func file_hallService_proto_rawDescGZIP() []byte {
	file_hallService_proto_rawDescOnce.Do(func() {
		file_hallService_proto_rawDescData = protoimpl.X.CompressGZIP(file_hallService_proto_rawDescData)
	})
	return file_hallService_proto_rawDescData
}

var file_hallService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hallService_proto_goTypes = []interface{}{
	(*Hall)(nil),                        // 0: proto.Hall
	(*CreateHallRequest)(nil),           // 1: proto.CreateHallRequest
	(*CreateHallResponse)(nil),          // 2: proto.CreateHallResponse
	(*GetHallRequest)(nil),              // 3: proto.GetHallRequest
	(*GetHallResponse)(nil),             // 4: proto.GetHallResponse
	(*UpdateHallAvailableRequest)(nil),  // 5: proto.UpdateHallAvailableRequest
	(*UpdateHallAvailableResponse)(nil), // 6: proto.UpdateHallAvailableResponse
	(*Movie)(nil),                       // 7: proto.Movie
}
var file_hallService_proto_depIdxs = []int32{
	7, // 0: proto.Hall.movie:type_name -> proto.Movie
	7, // 1: proto.CreateHallRequest.movie:type_name -> proto.Movie
	0, // 2: proto.CreateHallResponse.hall:type_name -> proto.Hall
	0, // 3: proto.GetHallResponse.hall:type_name -> proto.Hall
	0, // 4: proto.UpdateHallAvailableResponse.hall:type_name -> proto.Hall
	1, // 5: proto.HallService.CreateHall:input_type -> proto.CreateHallRequest
	3, // 6: proto.HallService.GetHall:input_type -> proto.GetHallRequest
	5, // 7: proto.HallService.UpdateHallAvailable:input_type -> proto.UpdateHallAvailableRequest
	2, // 8: proto.HallService.CreateHall:output_type -> proto.CreateHallResponse
	4, // 9: proto.HallService.GetHall:output_type -> proto.GetHallResponse
	6, // 10: proto.HallService.UpdateHallAvailable:output_type -> proto.UpdateHallAvailableResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_hallService_proto_init() }
func file_hallService_proto_init() {
	if File_hallService_proto != nil {
		return
	}
	file_movieService_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hallService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hallService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hallService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hallService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hallService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hallService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHallAvailableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hallService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHallAvailableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hallService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hallService_proto_goTypes,
		DependencyIndexes: file_hallService_proto_depIdxs,
		MessageInfos:      file_hallService_proto_msgTypes,
	}.Build()
	File_hallService_proto = out.File
	file_hallService_proto_rawDesc = nil
	file_hallService_proto_goTypes = nil
	file_hallService_proto_depIdxs = nil
}
